name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ 저장소 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # 3️⃣ Gradle 권한 부여 (Unix 환경)
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4️⃣ Gradle 빌드 & 테스트
      - name: Build and test with Gradle
        run: ./gradlew clean build